### ISSUE TITLE
"Exclude merge Commits" is not working as expected in YACC

### ISSUE THREAD

**Issue by sjothi** [mohamicorp/yet-another-commit-checker#98] opened 2015-12-29 06:36 UTC
Hi,
1. We have unchecked "Exclude Merge Commits" check box. This means even merge commits should checked against YACC rules. But that is not working.
Ex:
1. I had a regex test saying "test" in the "Commit Message Regex" box. But when i merge even without "test" text in the commit msg, its getting merged to the target branch.

Am i missing something here ? Help me.

Let me know if you need more information.

**Comment by sford** [comment] 2016-01-13 07:02
`Exclude Merge Commits` only applies to git _merge_ commits. IE, commits that include `Merge:` when doing `git log`. These typically have auto-generated commit messages. So, if you require JIRA issues in all commit messages, `Exclude Merge Commits` will tell YACC to skip merge commits with automatically generated messages.

In your example, are you suggesting that you are replacing the default git merge commit message?

More info might help... like turning on YACC debug logging or a snippet of `git log` to better understand what you are trying to do.

**Comment by george-vulov** [comment] 2020-07-23 23:25
I'm guessing the issue is that YACC only checks merges pushed via the command line, not merges made from the pull request UI. This is tracked on [YACC-256](https://mohamicorp.atlassian.net/browse/YACC-256), and we hope to have the fix released within the next few weeks.

**Closed by george-vulov** 2020-07-23 23:25 UTC
