### ISSUE TITLE
YACC does not check commits made via Bitbucket GUI

### ISSUE THREAD

**Issue by Rudy-Tmc** [mohamicorp/yet-another-commit-checker#140] opened 2017-01-27 10:50 UTC
Bitbucket 4.13 is incompatible.

Bitbucket has now the functionality of 'editing on the server'.
YACC does not seem to check the commits created via this functionality.

Regards,
Rudy

**Comment by sford** [comment] 2017-01-30 06:22
@Rudy-Tmc I temporarily removed 4.13 compatibility due to BBS 4.13 adding support for git 2.11, but YACC isn't compatible with git 2.11 yet. I actually just finished up some changes to YACC 1.13-SNAPSHOT to fix this, and will release it to the Atlassian Marketplace soon.

If you are not using git 2.11, YACC 1.12 should work fine if you install it manually (#137).

**Comment by sford** [comment] 2017-01-31 05:20
YACC 1.13 released with git 2.11 compatibility. I added back 4.13 compatibility for YACC 1.12, but you will need YACC 1.13 if you are using the latest git release.

Closing this out since root issue is fixed. I haven't had a chance to play with new edit feature, but feel free to open a new issue for it.

**Comment by Rudy-Tmc** [comment] 2017-01-31 05:47
Thanks Sean! 
That was solved really quickly!

**Comment by sford** [comment] 2017-02-01 07:40
Just a FYI, I was looking into the new file edit feature and found an [open BSERV ticket](https://jira.atlassian.com/browse/BSERV-9521) requesting the ability for plugins to validate commit message content when doing in-line edits. So it appears YACC support for it will have to wait until they add the APIs to allow it.

**Comment by Rudy-Tmc** [comment] 2017-02-01 09:16
Thanks for the info Sean, I really appreciate it.

**Comment by SandyMotyl** [comment] 2017-02-02 14:54
Thanks for the info about in-browser edit/commits and YACC and why you can't address it now.  

A couple people pointed out something that isn't mentioned in the documentation of the in-browser edit/commit feature.  In case others missed it too, you can disable the use of feature globally - https://answers.atlassian.com/questions/46800809/how-to-disable-file-content-editing-in-4.13.  Without this ability, this would have been a showstopper for us on 4.13.0 - we use YACC to enforce rules to implement our compliance mechanisms.

**Comment by agusmba** [comment] 2017-04-26 08:46
Hi @sford it seems [the BSERV ticket](https://jira.atlassian.com/browse/BSERV-9521) will be fixed in the next version (5.0).
Should we re-open this issue or create a new one?
Cheers!

**Comment by agusmba** [comment] 2017-04-26 08:50
If you reopen this issue it might be better to change the title to something more appropriate, such as "YACC does not check commits made via Bitbucket GUI" (just an example)

**Comment by sford** [comment] 2017-04-26 14:52
@agusmba I am glad they got that fixed! Re-opening works for me 👍

**Comment by alepe** [comment] 2017-11-15 11:37
Hi @sford
... we would be very glad to see this feature :) THX!
Regards Alexander

**Comment by esmaras** [comment] 2018-10-15 20:53
It looks like this issue may be resolved when Bitbucket 6.0 is released towards the end of the 2018. @agusmba you mentioned the BSERV ticket that then mentions using "FileEditRequestEvent" but now it seems that is deprecated and will be folded into "PreRepositoryHook<EditFileHookRequest>" indicated [here](https://docs.atlassian.com/bitbucket-server/javadoc/5.0.2/api/reference/com/atlassian/bitbucket/event/content/FileEditRequestedEvent.html#FileEditRequestedEvent(java.lang.Object,%20com.atlassian.bitbucket.repository.Repository,%20com.atlassian.bitbucket.util.CancelState,%20com.atlassian.bitbucket.repository.Branch,%20java.lang.String,%20com.atlassian.bitbucket.io.InputSupplier%3Cjava.io.InputStream%3E,%20java.lang.String)).

**Comment by rishibamba** [comment] 2019-01-03 11:07
Hi @sford ,
The [BSERV Ticket](https://jira.atlassian.com/browse/BSERV-9521) is Resolved. Does that mean it is live now ?

I am currently observing this behavior on Bitbucket Server v5.16.0 & YACC v1.22.

Thank You :)

**Comment by sford** [comment] 2019-01-12 17:17
Hi @rishibamba , YACC support isn't live or implemented yet for this.

This is next on my interest list.... wanted to get project-level settings in first and deal with DC support.

**Comment by PPFerrari** [comment] 2019-05-14 10:53
Does this issue affect also Pull Request message when the user accepts one?

**Comment by uanderso** [comment] 2019-09-09 09:30
This would be really really really really nice to have. Help users not to to merge code without and with wise PR messages readable to others, developers and testers. Then also extractable to be integrated in Release notes. Whats missing now, how can we help solve this?  (I'm new at github)

**Comment by sford** [comment] 2019-10-12 15:11
Error messages show up in file edit dialog as expected:
![image](https://user-images.githubusercontent.com/1066452/66703424-22a76e80-ecd8-11e9-8a2f-3f5a79a99689.png)

Old BBS versions (at least `5.2.0`) don't support return errors, so a generic "write permission denied" message is returned:
![image](https://user-images.githubusercontent.com/1066452/66703440-52567680-ecd8-11e9-814d-131e967e05f2.png)

Not much can be done about this though to return helpful messages in older BBS versions. Newer versions work as expected.

**Comment by CathySoMcK** [comment] 2019-10-14 12:38
@sford 
Will these messages trigger when committing via the Bitbucket Server REST API as well?  We have a project wanting us to enable the GUI edits so they can automate using REST but we have not been able to due to this issue.

**Comment by sford** [comment] 2019-10-15 22:46
Hi @CathySoMcK,

I am not familiar with committing files via BBS REST API. YACC just passes messages to BBS, who is responsible for returning them to the user. I would assume BBS would pass along message in API response just like GUI model, but I can't say for certain. If it didn't for some reason, it would probably be an easy feature request for BBS because API wouldn't be as helpful as it should.

**Comment by qwang-nj** [comment] 2019-12-17 19:10
@sford 
Atlassian Marketplace lists compatibility matrix for various releases of YACC plugin.  But it doesn't include the info for Git version.  Would you be able to help us with git compatibility?  Thank you in advance for your time.

**Comment by sford** [comment] 2019-12-17 19:33
Hi @qwang-nj , YACC should be fine as long as you are running supported git for your BBS version:
https://confluence.atlassian.com/bitbucketserver/supported-platforms-776640981.html

**Comment by qwang-nj** [comment] 2019-12-17 19:38
@sford - thank you for the clarification.

**Comment by sford** [comment] 2020-02-10 00:41
I still need to write some integration tests around this before I am comfortable uploading to market place... in meantime, I moved CI to Github Actions and added support for archiving plugin jar. 
1.25 SNAPSHOT can be downloaded here:
https://github.com/sford/yet-another-commit-checker/actions/runs/36750102

This jar can be installed in BBS plugin manager. 

If anyone is waiting for this and wants to help test it, any help would be appreciated!

**Comment by bharathnatarajan1** [comment] 2020-03-17 03:52
@sford I have tested following features and ensured it works successfully using YACC 1.25-SNAPSHOT jar in my BitBucket Environment:

- Commit message validation during Online edit in browser

- Commit message validation during code 'push' from Git Client to remote repository

- Commit message Jira Issue Key validation using Regex during code 'push' from Git Client to remote repository

- Issue JQL Matcher validation

It would be good to see the latest version of YACC in Atlassian Market place, so that we can adopt it in our BitBucket environments.

Let me know if you need any further help in testing.

**Comment by george-vulov** [comment] 2020-07-23 23:06
The fix for this is now released, see [version 1.25.0 on YACC Marketplace listing](https://marketplace.atlassian.com/apps/1211854/yet-another-commit-checker?hosting=server&tab=versions).

**Closed by george-vulov** 2020-07-23 23:06 UTC
Labels: type: feature

**Comment by christazelaar** [comment] 2020-07-23 23:33
Fantastic!

**Comment by cerebro84** [comment] 2020-07-28 14:28
If I understand correctly this doesn't apply to the pull request merge ui, right?

**Comment by george-vulov** [comment] 2020-07-28 18:23
@cerebro84 The fix released on 1.25 ensures that commits made via the "Edit" button in the Bitbucket UI are checked.

There's a separate bug, [tracked here](https://mohamicorp.atlassian.net/browse/YACC-256) where YACC doesn't check the merge commit created when merging a pull request, even if the "Exclude Merge Commits" option is disabled. (All the commits in the pull request are checked when they're pushed, the issue is with the merge commit only). We hope to have this fixed soon.

By the way, if you're finding Yacc useful, it would be very helpful for us to [leave a review](https://marketplace.atlassian.com/apps/1211854/yet-another-commit-checker?hosting=datacenter&tab=reviews) on the marketplace listing. Nobody has left a review in years.

**Comment by cerebro84** [comment] 2020-07-28 18:43
Thank you for the quick answer @george-vulov . Unfortunately without that feature we cannot really use it (so leave a review) because we don't want to have any restriction when committing/pushing on unprotected branches (in our case, feature branches) but we would like to avoid bad commit messages when merging to develop, that we only allow via pull requests. We'll be able to use the plugin only when that feature is available, but apart from that, it seems to have all the features we need in terms of customization.

**Comment by rhodessteve** [comment] 2020-12-10 11:34
@george-vulov where can we get a copy of YACC 1.26? As mentioned by you here mohamicorp.atlassian.net/browse/YACC-267 marketplace only lists 2.x now
