### ISSUE TITLE
Bamboo branch integration failure

### ISSUE THREAD

**Issue by k-brooks** [mohamicorp/yet-another-commit-checker#128] opened 2016-11-09 22:42 UTC
When attempting to use the Bamboo branch 'updater' feature, pushes fail with a name and email mismatch.
Relevant configuration information ->

- Require Matching Committer Email = true
- Require Matching Committer Name = true
- Exclude Merge Commits = true
- Exclude by Regex = \\[bamboo\\] Automated branch merge (this is the message)
- Exclude Service User Commits = true (SSH is being used)

The email and name which YACC expect (according to the failure message) are curious because no commits from that user are contained in the merge.

Bamboo branch updater: https://confluence.atlassian.com/bamboo0513/using-plan-branches-857079167.html#Usingplanbranches-Branchupdater

**Comment by george-vulov** [comment] 2020-07-24 00:21
This looks like a duplicate of #157 -- the email and name checks were applied prior to applying exclusions. This is now fixed; reference [version 1.25.0 of YACC on the Atlassian marketplace](https://marketplace.atlassian.com/apps/1211854/yet-another-commit-checker?hosting=server&tab=versions).

**Closed by george-vulov** 2020-07-24 00:21 UTC
