### ISSUE TITLE
If YACC hook is disabled at the repository level and enabled at the global level, it disregards the global level

### ISSUE THREAD

**Issue by coxcs1** [mohamicorp/yet-another-commit-checker#195] opened 2018-10-31 00:19 UTC
If YACC hook is disabled at the repository level and enabled at the global level, it disregards the global level. This is not desired as an organization we need global level to override so project admins cannot disable jira issue key check.. let me know if there is any plan to implement an option for this.
Thanks!

**Comment by sford** [comment] 2018-10-31 12:51
Hi @coxcs1 ,

What version of YACC are you using? The intention is for global level settings to take affect if YACC hook is disabled. There was a bug involving this where global settings wouldn't take affect if hook settings was toggled on/off.

[It was fixed in 1.19](https://github.com/sford/yet-another-commit-checker/blob/master/CHANGELOG.md#119-2018-03-24)... are you using <1.19 by any chance?

**Comment by coxcs1** [comment] 2018-11-01 13:53
We are using version 1.19...

**Comment by AtlassianUser** [comment] 2020-01-07 13:51
"If YACC hook is disabled at the repository level and enabled at the global level, it disregards the global level"
We have the same problem!

We don't want that the global settings of the YACC plugin can be deactivated on repository level. Is there now a way to do this? YACC Version: 1.24.

**Comment by george-vulov** [comment] 2020-07-15 18:30
Hi Crystal & AtlassianUser,

I tested this case and it could not reproduce the issue. Maybe the issue is with a specific setting or a combination of settings. Can you please provide the following additional information?

1. Screenshot of the YACC global settings page. You can use [this plugin](https://addons.mozilla.org/en-US/firefox/addon/easyscreenshot) to capture the whole page easily without scrolling.
2. Screenshot of the YACC repository-revel configuration (should just show the hook is disabled).

Thanks!

**Comment by george-vulov** [comment] 2020-07-25 02:42
@coxcs1 This is a pretty old issue, so I'm going to close it for now. Please feel free to open a support request in the [mohami support portal](https://mohamicorp.atlassian.net/servicedesk/customer/portals) if you're still experiencing this problem.

**Closed by george-vulov** 2020-07-25 02:42 UTC
